'''
Question :

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

by Sandeep kumar ,31/3/17
'''



limit=4000000                      #the limit
sum=0
a=1
b=1
c=a+b
while c<limit:   
 sum=sum+c                        # adding every third element
 a=b+c
 b=c+a
 c=a+b


print(sum)                        #printing the sum
 
